src/main/java/itakademija/java2015/myapp/entities/Coupon.java
package itakademija.java2015.myapp.entities;

import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Coupon {

    @Id
    @GeneratedValue
    private Long id;

    private String serial;

    @Temporal(TemporalType.DATE)
    private Date couponDate;

    private String seller;

    private String buyer;

    @OneToMany(mappedBy = "coupon", orphanRemoval = true, fetch = FetchType.EAGER)
    private List<Item> items;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSerial() {
        return serial;
    }

    public void setSerial(String serial) {
        this.serial = serial;
    }

    public Date getCouponDate() {
        return couponDate;
    }

    public void setCouponDate(Date couponDate) {
        this.couponDate = couponDate;
    }

    public String getSeller() {
        return seller;
    }

    public void setSeller(String seller) {
        this.seller = seller;
    }

    public String getBuyer() {
        return buyer;
    }

    public void setBuyer(String buyer) {
        this.buyer = buyer;
    }

    public List<Item> getItems() {
        return items;
    }

    public void setItems(List<Item> items) {
        this.items = items;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((serial == null) ? 0 : serial.hashCode());
        result = prime * result + ((seller == null) ? 0 : seller.hashCode());
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof Coupon)) {
            return false;
        }
        Coupon other = (Coupon) obj;
        if (serial == null) {
            if (other.serial != null) {
                return false;
            }
        } else if (!serial.equals(other.serial)) {
            return false;
        }
        if (id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!id.equals(other.id)) {
            return false;
        }
        return true;
    }
}

src/main/java/itakademija/java2015/myapp/entities/Item.java
package itakademija.java2015.myapp.entities;

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity
public class Item {

    @Id
    @GeneratedValue
    private Long id;
    private String name;
    private Integer amount;
    private String units;
    private BigDecimal price;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "coupon_id")
    private Coupon coupon;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Coupon getCoupon() {
        return coupon;
    }

    public void setCoupon(Coupon coupon) {
        this.coupon = coupon;
    }

    @Override
    public String toString() {
        return ("item id: " + id + " name: " + name);
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public String getUnits() {
        return units;
    }

    public void setUnits(String units) {
        this.units = units;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

}

src/main/java/itakademija/java2015/myapp/entities/repositories/CouponRepository.java
package itakademija.java2015.myapp.entities.repositories;

import itakademija.java2015.myapp.entities.Coupon;

import java.util.List;

public interface CouponRepository {

    void save(Coupon newCoupon);

    void delete(Coupon coupon);

    List<Coupon> findAll();

    Coupon findById(Long id);

    Long countCoupons();

}

src/main/java/itakademija/java2015/myapp/entities/repositories/ItemRepository.java
package itakademija.java2015.myapp.entities.repositories;

import itakademija.java2015.myapp.entities.Coupon;
import itakademija.java2015.myapp.entities.Item;

import java.util.List;

public interface ItemRepository {

    public void save(Item newCoupon);

    public void delete(Item item);

    public List<Item> findAll();

    public List<Item> findAllByCoupon(Coupon coupon);

    public Number countItemsByPriceInterval(int min, int max,
            boolean countSpecial, int specialThreshold);

    public Long countItemsByCouponId(Coupon coupon);

}

src/main/java/itakademija/java2015/myapp/ui/models/CouponModel.java
package itakademija.java2015.myapp.ui.models;

import itakademija.java2015.myapp.entities.Coupon;

import java.io.Serializable;

import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CouponModel implements Serializable {

    private static final long serialVersionUID = 5040310448257955354L;

    static final Logger log = LoggerFactory.getLogger(CouponModel.class);

    public void destroy() {
        log.warn("Bean destroyed");
    }

    @Valid
    private Coupon currentCoupon;

    public void init() {
        log.warn("Bean created");
        currentCoupon = new Coupon();
    }

    public Coupon getCurrentCoupon() {
        return currentCoupon;
    }

    public void setCurrentCoupon(Coupon currentCoupon) {
        this.currentCoupon = currentCoupon;
    }

}

src/main/java/itakademija/java2015/myapp/ui/models/ItemModel.java
package itakademija.java2015.myapp.ui.models;

import itakademija.java2015.myapp.entities.Item;

import java.io.Serializable;

import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ItemModel implements Serializable {

    private static final long serialVersionUID = -8131673305859876205L;

    static final Logger log = LoggerFactory.getLogger(CouponModel.class);

    public void destroy() {
        log.warn("Bean destroyed");
    }

    @Valid
    private Item currentItem;

    public void init() {
        log.warn("Bean created");
        currentItem = new Item();
    }

    public Item getCurrentItem() {
        return currentItem;
    }

    public void setCurrentItem(Item currentItem) {
        this.currentItem = currentItem;
    }
}

src/main/java/itakademija/java2015/myapp/ui/controllers/CouponController.java
package itakademija.java2015.myapp.ui.controllers;

import itakademija.java2015.myapp.entities.Coupon;
import itakademija.java2015.myapp.entities.Item;
import itakademija.java2015.myapp.services.CouponService;
import itakademija.java2015.myapp.ui.models.CouponModel;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CouponController implements Serializable {

    private static final long serialVersionUID = -8143077418240345336L;

    static final Logger log = LoggerFactory.getLogger(CouponController.class);

    public void init() {
        log.warn("Bean created");
    }

    public void destroy() {
        log.warn("Bean destroyed");
    }

    public static final String NAV_LIST_COUPONS = "list-coupons";
    public static final String NAV_LIST_ITEMS = "list-items";
    public static final String EUR_TO_LT = "3.4528";

    private CouponModel couponModel;
    private CouponService couponService;

    public BigDecimal calculateCouponTotal(Coupon coupon) {
        BigDecimal couponTotal = BigDecimal.ZERO;
        List<Item> items = coupon.getItems();
        for (Item item : items) {
            BigDecimal itemTotal = item.getPrice().multiply(new BigDecimal(item.getAmount()));
            couponTotal = couponTotal.add(itemTotal);
        }
        return couponTotal;
    }

    public BigDecimal calculateTotalInLT(Coupon coupon) {
        BigDecimal couponTotal = calculateCouponTotal(coupon);
        couponTotal = couponTotal.multiply(new BigDecimal(EUR_TO_LT));
        couponTotal = couponTotal.setScale(2, BigDecimal.ROUND_HALF_EVEN);
        return couponTotal;
    }

    public String calculateBarcode() {
        int barcodeLengthNoChecksum = 12;
        String barcode = "00000000";
        if (couponModel != null && couponModel.getCurrentCoupon() != null) {
            Date couponDate = couponModel.getCurrentCoupon().getCouponDate();
            if (couponDate != null) {
                barcode = String.valueOf(couponDate.getTime()).substring(0, 8);
            }
            try {
                int id = Integer.parseInt(couponModel.getCurrentCoupon().getSerial());
                barcode = barcode + id;
            } catch (Exception ex) {
                log.debug("Serial not a number, can't use for barcode");
            }
            if (barcode.length() < barcodeLengthNoChecksum) {
                int addZeroes = barcodeLengthNoChecksum - barcode.length();
                for (int i = 0; i < addZeroes; i++) {
                    barcode = barcode + "0";
                }
            } else if (barcode.length() > barcodeLengthNoChecksum) {
                barcode = barcode.substring(0, barcodeLengthNoChecksum);
            }
        }
        return barcode;
    }

    public void updateGrowl() {
        Long couponCount = couponService.countCoupons();
        if (couponCount < 2) {
            FacesMessage warningMessage = new FacesMessage("At least 2 coupons are required");
            FacesContext.getCurrentInstance().addMessage(null, warningMessage);
        }
    }

    public void create() {
        couponModel.setCurrentCoupon(new Coupon());
    }

    public String delete(Coupon coupon) {
        couponService.delete(coupon);
        return NAV_LIST_COUPONS;
    }

    public List<Coupon> getCouponList() {
        return couponService.findAll();
    }

    public List<Item> findItemsByCoupon() {
        return couponModel.getCurrentCoupon().getItems();
    }

    public List<Item> getFreshItemList() {
        Long currentCouponId = couponModel.getCurrentCoupon().getId();
        if (currentCouponId == null) return null;
        return couponService.findById(currentCouponId).getItems();
    }

    public String update(Coupon coupon) {
        couponModel.setCurrentCoupon(coupon);
        return NAV_LIST_ITEMS;
    }

    public String save() {
        couponService.save(couponModel.getCurrentCoupon());
        return NAV_LIST_COUPONS;
    }

    public String cancel() {
        couponModel.setCurrentCoupon(new Coupon());
        return NAV_LIST_COUPONS;
    }

    public CouponModel getCouponModel() {
        return couponModel;
    }

    public void setCouponModel(CouponModel couponModel) {
        this.couponModel = couponModel;
    }

    public CouponService getCouponService() {
        return couponService;
    }

    public void setCouponService(CouponService couponService) {
        this.couponService = couponService;
    }

}

src/main/java/itakademija/java2015/myapp/ui/controllers/ItemController.java
package itakademija.java2015.myapp.ui.controllers;

import itakademija.java2015.myapp.entities.Item;
import itakademija.java2015.myapp.services.ItemService;
import itakademija.java2015.myapp.ui.models.CouponModel;
import itakademija.java2015.myapp.ui.models.ItemModel;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Map;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.CategoryAxis;
import org.primefaces.model.chart.ChartSeries;
import org.primefaces.model.chart.LineChartModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ItemController implements Serializable {

    private static final long serialVersionUID = -1389684115871062390L;

    static final Logger log = LoggerFactory.getLogger(ItemController.class);

    public void init() {
        log.warn("Bean created");
    }

    public void destroy() {
        log.warn("Bean destroyed");
    }

    private CouponModel couponModel;
    private ItemModel itemModel;
    private ItemService itemService;

    public BigDecimal calculateItemTotal(Item item) {
        BigDecimal itemTotal = item.getPrice().multiply(new BigDecimal(item.getAmount()));
        return itemTotal;
    }

    public LineChartModel calculateLineModel() {
        int specialThreshold = 2;
        LineChartModel model = new LineChartModel();
        ChartSeries specialItems = new ChartSeries();
        specialItems.setLabel("Special Items (2 or less)");
        specialItems.set("0-9", itemService.countItemsByPriceInterval(0, 9, true, specialThreshold));
        specialItems.set("10-49", itemService.countItemsByPriceInterval(10, 49, true, specialThreshold));
        specialItems.set("50-99", itemService.countItemsByPriceInterval(50, 99, true, specialThreshold));
        specialItems.set("100-3455", itemService.countItemsByPriceInterval(100, 3455, true, specialThreshold));
        specialItems.set("3456 and more", itemService.countItemsByPriceInterval(3456, Integer.MAX_VALUE, true, specialThreshold));
        ChartSeries massProdItems = new ChartSeries();
        massProdItems.setLabel("Mass Produced Items (3 or more)");
        massProdItems.set("0-9", itemService.countItemsByPriceInterval(0, 9, false, specialThreshold));
        massProdItems.set("10-49", itemService.countItemsByPriceInterval(10, 49, false, specialThreshold));
        massProdItems.set("50-99", itemService.countItemsByPriceInterval(50, 99, false, specialThreshold));
        massProdItems.set("100-3455", itemService.countItemsByPriceInterval(100, 3455, false, specialThreshold));
        massProdItems.set("3456 and more", itemService.countItemsByPriceInterval(3456, Integer.MAX_VALUE, false, specialThreshold));
        model.addSeries(specialItems);
        model.addSeries(massProdItems);
        model.setTitle("Items by Price Intervals");
        model.setLegendPosition("e");
        model.setShowPointLabels(true);
        Axis yAxis = model.getAxis(AxisType.Y);
        yAxis.setLabel("Units");
        yAxis.setMin(0);
        int max = 40;
        max = adjustMaxForDataset(max, specialItems.getData());
        max = adjustMaxForDataset(max, massProdItems.getData());
        yAxis.setMax(max);
        model.getAxes().put(AxisType.X, new CategoryAxis("Price Intervals"));
        return model;
    }

    private int adjustMaxForDataset(int max, Map<Object, Number> data) {
        for (Number num : data.values()) {
            if (max - 10 < (Integer) num) {
                max = (Integer) num + 10;
            }
        }
        return max;
    }

    public void create() {
        itemModel.setCurrentItem(new Item());
    }

    public void update(Item item) {
        itemModel.setCurrentItem(item);
    }

    public String save() {
        itemModel.getCurrentItem().setCoupon(couponModel.getCurrentCoupon());
        itemService.save(itemModel.getCurrentItem());
        itemModel.setCurrentItem(new Item());
        return CouponController.NAV_LIST_ITEMS;
    }

    public void updateGrowl() {
        if (couponModel == null || couponModel.getCurrentCoupon() == null) {
            return;
        }
        Long itemCount = itemService.countItemsByCouponId(couponModel.getCurrentCoupon());
        if (itemCount == 0) {
            FacesMessage warningMessage = new FacesMessage("A coupon must have at least 1 item");
            FacesContext.getCurrentInstance().addMessage(null, warningMessage);
        }
    }

    public String delete(Item item) {
        itemService.delete(item);
        updateGrowl();
        return CouponController.NAV_LIST_ITEMS;
    }

    public String cancel() {
        itemModel.setCurrentItem(new Item());
        return CouponController.NAV_LIST_ITEMS;
    }

    public ItemModel getItemModel() {
        return itemModel;
    }
    public void setItemModel(ItemModel itemModel) {
        this.itemModel = itemModel;
    }

    public ItemService getItemService() {
        return itemService;
    }

    public void setItemService(ItemService itemService) {
        this.itemService = itemService;
    }

    public CouponModel getCouponModel() {
        return couponModel;
    }

    public void setCouponModel(CouponModel couponModel) {
        this.couponModel = couponModel;
    }
}

src/main/webapp/coupons.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets" template="layout.xhtml">

    <ui:define name="content">
        <h:form id="dataTable">
            <p:growl id="growl" sticky="true" />
            <p:remoteCommand name="onload" action="#{couponController.updateGrowl()}" autoRun="true" update="growl"/>
            <p:dataTable value="#{couponController.couponList}" var="coupon">
                <f:facet name="header">All Coupons</f:facet>
                <p:column headerText="Serial">
                    <h:outputText value="#{coupon.serial}" />
                </p:column>
                <p:column headerText="Date">
                    <h:outputText value="#{coupon.couponDate}" />
                </p:column>
                <p:column headerText="Seller">
                    <h:outputText value="#{coupon.seller}" />
                </p:column>
                <p:column headerText="Buyer">
                    <h:outputText value="#{coupon.buyer}" />
                </p:column>
                <p:column headerText="Total, Eur">
                    <h:outputText value="#{couponController.calculateCouponTotal(coupon)}" />
                </p:column>
                <p:column headerText="Total, Lt">
                    <h:outputText value="#{couponController.calculateTotalInLT(coupon)}" />
                </p:column>
                <p:column headerText="">
                    <p:commandButton value="Open"
                        action="#{couponController.update(coupon)}">
                    </p:commandButton>
                </p:column>
                <p:column headerText="">
                    <p:commandButton value="Delete"
                        action="#{couponController.delete(coupon)}">
                        <p:confirm header="Confirmation" message="Are you sure?"
                            icon="ui-icon-alert" />
                    </p:commandButton>
                    <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                        <p:commandButton value="Yes" type="button"
                            styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                        <p:commandButton value="No" type="button"
                            styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                    </p:confirmDialog>
                </p:column>
            </p:dataTable>
        </h:form>
        <p:commandButton action="#{couponController.create}"
            update="updateForm" value="Create coupon"
            oncomplete="PF('createCoupon').show();" />
        <p:commandButton action="#{itemController.create}"
            update="itemForm" value="Add new item"
            oncomplete="PF('createItem').show();" />
        <p:chart id="chart1" type="line" model="#{itemController.calculateLineModel()}"/>
        <p:dialog header="Create Coupon" widgetVar="createCoupon"
            modal="true" showEffect="fade" hideEffect="fade"
            resizable="false">
            <h:form id="updateForm">
                <p:outputPanel rendered="#{couponModel.currentCoupon != null}">
                    <h:panelGrid columns="3" cellpadding="5">
                        <p:outputLabel for="serial">Serial:</p:outputLabel>
                        <p:inputText id="serial"
                            value="#{couponController.couponModel.currentCoupon.serial}"
                            required="true">
                            <f:validateLength minimum="2" maximum="14"/>
                            <p:ajax event="valueChange"
                            onstart="#{couponController.calculateBarcode()}" update="barcode2"/>
                        </p:inputText>
                        <p:message for="serial"></p:message>
                        
                        <p:outputLabel for="couponDate">Date:</p:outputLabel>
                        <p:calendar id="couponDate"
                            value="#{couponController.couponModel.currentCoupon.couponDate}">
                            <p:ajax event="dateSelect"
                            oncomplete="#{couponController.calculateBarcode()}" update="barcode2"/>
                        </p:calendar>
                        <p:message for="couponDate"></p:message>
                        
                        <p:outputLabel for="seller">Seller:</p:outputLabel>
                        <p:inputText id="seller"
                            value="#{couponController.couponModel.currentCoupon.seller}">
                            <f:validateLength maximum="255"/>
                        </p:inputText>
                        <p:message for="seller"></p:message>

                        <p:outputLabel for="buyer">Buyer:</p:outputLabel>
                        <p:inputText id="buyer"
                            value="#{couponController.couponModel.currentCoupon.buyer}">
                            <f:validateLength maximum="255"/>
                        </p:inputText>
                        <p:message for="buyer"></p:message>
                        
                        <h:outputText value="EAN-13" />
                        <p:barcode id="barcode2" value="#{couponController.calculateBarcode()}" type="ean13" format="png">
                        </p:barcode>
                        <p:message for="barcode2"></p:message>

                        <p:commandButton value="Save"
                            actionListener="#{couponController.save}"
                            update="updateForm dataTable"
                            oncomplete="if (!args.validationFailed) PF('createCoupon').hide();">
                        </p:commandButton>
                        <p:commandButton value="Cancel"
                            actionListener="#{couponController.cancel}"
                            update="updateForm dataTable"
                            oncomplete="PF('createCoupon').hide();" immediate="true">
                        </p:commandButton>
                    </h:panelGrid>
                </p:outputPanel>
            </h:form>
        </p:dialog>
        <p:dialog header="Create Item" widgetVar="createItem"
            modal="true" showEffect="fade" hideEffect="fade"
            resizable="false">
            <h:form id="itemForm">
                <p:outputPanel rendered="#{itemModel.currentItem != null}">
                    <h:panelGrid columns="3" cellpadding="5">
                        <h:outputLabel for="coupon" value="Coupon"></h:outputLabel>
                        <p:selectOneMenu id="coupon"
                            value="#{couponController.couponModel.currentCoupon}"
                            converter="#{couponConverter}"
                            required="true">
                            <f:selectItem itemValue="#{null}" itemLabel="Not selected"
                                noSelectionOption="true">
                            </f:selectItem>
                            <f:selectItems
                                value="#{couponController.getCouponList()}" 
                                var="listedCoupon" itemValue="#{listedCoupon}"
                                itemLabel="#{listedCoupon.getSerial()}"/>
                        </p:selectOneMenu>
                        <p:message for="coupon"></p:message>
                        
                        <p:outputLabel for="name">Name:</p:outputLabel>
                        <p:inputText id="name"
                            value="#{itemController.itemModel.currentItem.name}">
                            <f:validateLength maximum="255"/>
                        </p:inputText>
                        <p:message for="name"></p:message>

                        <p:outputLabel for="amount">Amount:</p:outputLabel>
                        <p:inputText id="amount"
                            value="#{itemController.itemModel.currentItem.amount}">
                            <f:validator binding="#{positiveNumberValidator}" />
                        </p:inputText>
                        <p:message for="amount"></p:message>

                        <p:outputLabel for="units">Units:</p:outputLabel>
                        <p:inputText id="units"
                            value="#{itemController.itemModel.currentItem.units}">
                            <f:validateLength maximum="255"/>
                        </p:inputText>
                        <p:message for="units"></p:message>

                        <p:outputLabel for="price">Price:</p:outputLabel>
                        <p:inputText id="price"
                            value="#{itemController.itemModel.currentItem.price}">
                            <f:convertNumber type="number"/>
                            <f:validator binding="#{positiveNumberValidator}" />
                        </p:inputText>
                        <p:message for="price"></p:message>

                        <p:commandButton value="Save"
                            actionListener="#{itemController.save}"
                            update="itemForm dataTable chart1"
                            oncomplete="if (!args.validationFailed) PF('createItem').hide();">
                        </p:commandButton>
                        <p:commandButton value="Cancel"
                            actionListener="#{itemController.cancel}"
                            update="itemForm"
                            oncomplete="PF('createItem').hide();" immediate="true">
                        </p:commandButton>
                    </h:panelGrid>
                </p:outputPanel>
            </h:form>
        </p:dialog>
    </ui:define>

    <ui:define name="title">
          All coupons
      </ui:define>

</ui:composition>

src/main/webapp/footer.xhtml
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head></h:head>
<h:body>
    <ui:composition>
        <div id="discount"></div>
    </ui:composition>
</h:body>
</h:html>

src/main/webapp/layout.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <title>Coupons: 
        <ui:insert name="title">
            No title
        </ui:insert>
    </title>
    <h:outputStylesheet name="style.css"></h:outputStylesheet>
</h:head>
<h:body>
    <div id="container">
        <div id="menu">
            <h:form>
                <p:tabMenu>
                    <p:menuitem value="Coupons" outcome="list-coupons" icon="ui-icon-scissors">
                    </p:menuitem>
                </p:tabMenu>
            </h:form>
        </div>
        <div id="layout">
            <div id="leftside">
                <ui:insert name="leftside" />
            </div>
            <div id="rightside">
                <ui:insert name="rightside" />
            </div>
        </div>
        <div id="contents">
            <ui:insert name="content" />
        </div>
    </div>
    <div id="footer-container">
        <ui:insert name="footer" />
    </div>
</h:body>
</html>